/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru
// SshKeyListResponse Response returned by User SSH Key List.
type SshKeyListResponse struct {
	// keyvalue
	Keyname string `json:"keyname,omitempty"`
}
