/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru
// ServiceBrokerConfigAuthConfigBasicAuthConfig struct for ServiceBrokerConfigAuthConfigBasicAuthConfig
type ServiceBrokerConfigAuthConfigBasicAuthConfig struct {
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}
