/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Data sent to the environment unset endpoint.
type EnvUnsetData struct {
	Env []string `json:"env,omitempty"`

	Norestart bool `json:"norestart,omitempty"`
}
