/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.19
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// App plan.
type Plan struct {
	Name     string       `json:"name,omitempty"`
	Memory   int64        `json:"memory,omitempty"`
	Cpumilli int32        `json:"cpumilli,omitempty"`
	CpuBurst PlanCpuBurst `json:"cpuBurst,omitempty"`
	Default  bool         `json:"default,omitempty"`
	Override PlanOverride `json:"override,omitempty"`
}
