/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.27
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type PlanCpuBurst struct {
	Default    float64 `json:"default,omitempty"`
	MaxAllowed float64 `json:"maxAllowed,omitempty"`
}
