/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Tsuru app.
type App struct {
	// App name.
	Name interface{} `json:"name"`
	// App tags.
	Tags interface{} `json:"tags,omitempty"`
	// App router.
	Router interface{} `json:"router,omitempty"`
	// Custom router options.
	Routeropts interface{} `json:"routeropts,omitempty"`
	Plan       interface{} `json:"plan,omitempty"`
	// App pool.
	Pool interface{} `json:"pool,omitempty"`
	// App platform.
	Platform interface{} `json:"platform,omitempty"`
	// App description.
	Description interface{} `json:"description,omitempty"`
	// Team that owns the app.
	TeamOwner interface{} `json:"teamOwner,omitempty"`
	Teams     interface{} `json:"teams,omitempty"`
	Cname     interface{} `json:"cname,omitempty"`
	Ip        interface{} `json:"ip,omitempty"`
	Owner     interface{} `json:"owner,omitempty"`
}
