/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

import (
	"time"
)

type EventCancelInfo struct {
	Asked     bool      `json:"Asked,omitempty"`
	Owner     string    `json:"Owner,omitempty"`
	AckTime   time.Time `json:"AckTime,omitempty"`
	StartTime time.Time `json:"StartTime,omitempty"`
	Canceled  bool      `json:"Canceled,omitempty"`
	Reason    string    `json:"Reason,omitempty"`
}
