/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Quota struct {
	Inuse interface{} `json:"inuse,omitempty"`
	Limit interface{} `json:"limit,omitempty"`
}
