/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Arguments for creating a new team token.
type TeamTokenCreateArgs struct {
	TokenId     interface{} `json:"token_id,omitempty"`
	Description interface{} `json:"description,omitempty"`
	// Expire time in seconds.
	ExpiresIn interface{} `json:"expires_in,omitempty"`
	Team      interface{} `json:"team,omitempty"`
}
