/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// EventCancelArgs struct for EventCancelArgs
type EventCancelArgs struct {
	Reason string `json:"reason,omitempty"`
}
