/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Assign role to group arguments.
type AssignGroupArgs struct {
	GroupName string `json:"group_name,omitempty"`
	Context   string `json:"context,omitempty"`
}
