/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Volume plan.
type VolumePlan struct {
	// Volume plan name.
	Name interface{} `json:"name,omitempty"`
	// Volume plan opts.
	Opts interface{} `json:"opts,omitempty"`
}
