/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ClusterHelp struct {
	ProvisionerHelp interface{} `json:"provisioner_help,omitempty"`
	CustomDataHelp  interface{} `json:"custom_data_help,omitempty"`
	CreateDataHelp  interface{} `json:"create_data_help,omitempty"`
}
