/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.20
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type ServiceInstance struct {
	Name        string                     `json:"name,omitempty"`
	Tags        []string                   `json:"tags,omitempty"`
	Id          int32                      `json:"id,omitempty"`
	ServiceName string                     `json:"service_name,omitempty"`
	PlanName    string                     `json:"plan_name,omitempty"`
	Apps        []string                   `json:"apps,omitempty"`
	Jobs        []string                   `json:"jobs,omitempty"`
	BoundUnits  []ServiceInstanceBoundUnit `json:"bound_units,omitempty"`
	Teams       []string                   `json:"teams,omitempty"`
	TeamOwner   string                     `json:"team_owner,omitempty"`
	Description string                     `json:"description,omitempty"`
	Parameters  map[string]string          `json:"parameters,omitempty"`
	Pool        string                     `json:"pool,omitempty"`
}
