/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ServiceInstanceUpdateData struct {
	Description interface{} `json:"description,omitempty"`
	Teamowner   interface{} `json:"teamowner,omitempty"`
	Plan        interface{} `json:"plan,omitempty"`
	Tags        interface{} `json:"tags,omitempty"`
}
