/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type AppProcessesTweak struct {
	Metadata Metadata `json:"metadata,omitempty"`
	Name     string   `json:"name,omitempty"`
}
