/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// ServiceBrokerConfig struct for ServiceBrokerConfig
type ServiceBrokerConfig struct {
	Insecure               bool                          `json:"Insecure,omitempty"`
	Context                map[string]string             `json:"Context,omitempty"`
	AuthConfig             ServiceBrokerConfigAuthConfig `json:"AuthConfig,omitempty"`
	CacheExpirationSeconds int32                         `json:"CacheExpirationSeconds,omitempty"`
}
