/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.27
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Behavior settings for scaling actions
type AutoScaleSpecBehavior struct {
	ScaleDown AutoScaleSpecBehaviorScaleDown `json:"scaleDown,omitempty"`
}
