/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type PoolUpdateData struct {
	Default_ interface{} `json:"default,omitempty"`
	Public   interface{} `json:"public,omitempty"`
	Force    interface{} `json:"force,omitempty"`
}
