/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type AppCertificatesRouters struct {
	Cnames map[string]AppCertificatesCnames `json:"cnames"`
}
