/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ServiceBroker struct {
	Name   interface{} `json:"Name,omitempty"`
	URL    interface{} `json:"URL,omitempty"`
	Config interface{} `json:"Config,omitempty"`
}
