/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Association between a role and a context value.
type RoleInstance struct {
	Name         interface{} `json:"name,omitempty"`
	Contextvalue interface{} `json:"contextvalue,omitempty"`
}
