/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Newly created app information.
type AppCreateResponse struct {
	Status        interface{} `json:"status,omitempty"`
	RepositoryUrl interface{} `json:"repository_url,omitempty"`
	Ip            interface{} `json:"ip,omitempty"`
}
