/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Router struct {
	Name         interface{} `json:"name,omitempty"`
	Opts         interface{} `json:"opts,omitempty"`
	Addres       interface{} `json:"addres,omitempty"`
	Type_        interface{} `json:"type,omitempty"`
	Status       interface{} `json:"status,omitempty"`
	StatusDetail interface{} `json:"status-detail,omitempty"`
}
