/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// An authorization token associated to a team.
type TeamToken struct {
	Token        interface{} `json:"token,omitempty"`
	TokenId      interface{} `json:"token_id,omitempty"`
	Description  interface{} `json:"description,omitempty"`
	CreatedAt    interface{} `json:"created_at,omitempty"`
	ExpiresAt    interface{} `json:"expires_at,omitempty"`
	LastAccess   interface{} `json:"last_access,omitempty"`
	CreatorEmail interface{} `json:"creator_email,omitempty"`
	Team         interface{} `json:"team,omitempty"`
	Roles        interface{} `json:"roles,omitempty"`
}
