/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.20
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type Provisioner struct {
	Name        string      `json:"name,omitempty"`
	ClusterHelp ClusterHelp `json:"cluster_help,omitempty"`
}
