/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type AppCreateData struct {
	// App name.
	Name string `json:"name"`
	// App tags.
	Tags []string `json:"tags,omitempty"`
	// App router name.
	Router string `json:"router,omitempty"`
	// Custom router options.
	Routeropts map[string]string `json:"routeropts,omitempty"`
	// App plan name.
	Plan string `json:"plan,omitempty"`
	// App pool name.
	Pool string `json:"pool,omitempty"`
	// App platform.
	Platform string `json:"platform,omitempty"`
	// App description.
	Description string `json:"description,omitempty"`
	// Team that owns the app.
	TeamOwner string `json:"teamOwner,omitempty"`
}
