/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Default a role
type RoleDefaultData struct {
	Rolesmap map[string][]string `json:"rolesmap,omitempty"`
}
