/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Machine struct {
	Id             interface{} `json:"id,omitempty"`
	Iaas           interface{} `json:"iaas,omitempty"`
	Address        interface{} `json:"address,omitempty"`
	Port           interface{} `json:"port,omitempty"`
	Protocol       interface{} `json:"protocol,omitempty"`
	Creationparams interface{} `json:"creationparams,omitempty"`
}
