/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ChangePasswordData struct {
	Confirm interface{} `json:"confirm,omitempty"`
	New     interface{} `json:"new,omitempty"`
	Old     interface{} `json:"old,omitempty"`
}
