/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Node struct {
	Address     interface{} `json:"address,omitempty"`
	Iaasid      interface{} `json:"iaasid,omitempty"`
	Status      interface{} `json:"status,omitempty"`
	Pool        interface{} `json:"pool,omitempty"`
	Provisioner interface{} `json:"provisioner,omitempty"`
	Metadata    interface{} `json:"metadata,omitempty"`
}
