/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.20
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

import (
	"time"
)

// Stores information about a lock hold on the app
type AppLock struct {
	Locked      bool      `json:"locked,omitempty"`
	Reason      string    `json:"reason,omitempty"`
	Owner       string    `json:"owner,omitempty"`
	AcquireDate time.Time `json:"acquireDate,omitempty"`
}
