/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

import (
	"time"
)

// Tracked instance information
type EventTrackedInstance struct {
	Name       string    `json:"Name,omitempty"`
	Port       string    `json:"Port,omitempty"`
	TLSPort    string    `json:"TLSPort,omitempty"`
	Addresses  []string  `json:"Addresses,omitempty"`
	LastUpdate time.Time `json:"LastUpdate,omitempty"`
}
