/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Service instance bind
type AppServiceInstanceBinds struct {
	Instance string `json:"instance,omitempty"`
	Service  string `json:"service,omitempty"`
	Plan     string `json:"plan,omitempty"`
}
