/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Role of an user.
type RoleUser struct {
	Name         interface{} `json:"name,omitempty"`
	Contexttype  interface{} `json:"contexttype,omitempty"`
	Contextvalue interface{} `json:"contextvalue,omitempty"`
}
