/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type TeamInfo struct {
	Name  interface{} `json:"name,omitempty"`
	Tags  interface{} `json:"tags,omitempty"`
	Users interface{} `json:"users,omitempty"`
	Pools interface{} `json:"pools,omitempty"`
	Apps  interface{} `json:"apps,omitempty"`
}
