/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ServiceInstanceInfo struct {
	Apps            interface{} `json:"apps,omitempty"`
	Teams           interface{} `json:"teams,omitempty"`
	Teamowner       interface{} `json:"teamowner,omitempty"`
	Description     interface{} `json:"description,omitempty"`
	Planname        interface{} `json:"planname,omitempty"`
	Plandescription interface{} `json:"plandescription,omitempty"`
	Tags            interface{} `json:"tags,omitempty"`
	Custominfo      interface{} `json:"custominfo,omitempty"`
}
