/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.27
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type AppStartStop struct {
	Process string `json:"process,omitempty"`
	Version string `json:"version,omitempty"`
}
