/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type SshKeyAddData struct {
	Force   interface{} `json:"force,omitempty"`
	Key     interface{} `json:"key,omitempty"`
	Keyname interface{} `json:"keyname,omitempty"`
}
