/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.15
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

import (
	"time"
)

// Tsuru event
type Event struct {
	UniqueID        string               `json:"UniqueID,omitempty"`
	StartTime       time.Time            `json:"StartTime,omitempty"`
	EndTime         time.Time            `json:"EndTime,omitempty"`
	Target          EventTarget          `json:"Target,omitempty"`
	StartCustomData EventStartCustomData `json:"StartCustomData,omitempty"`
	EndCustomData   EventStartCustomData `json:"EndCustomData,omitempty"`
	OtherCustomData EventStartCustomData `json:"OtherCustomData,omitempty"`
	Error           string               `json:"Error,omitempty"`
	Log             string               `json:"Log,omitempty"`
	Running         bool                 `json:"Running,omitempty"`
}
