/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.14
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type Cluster struct {
	Name        string            `json:"name,omitempty"`
	Addresses   []string          `json:"addresses,omitempty"`
	Provisioner string            `json:"provisioner,omitempty"`
	Cacert      []byte            `json:"cacert,omitempty"`
	Clientcert  []byte            `json:"clientcert,omitempty"`
	Clientkey   []byte            `json:"clientkey,omitempty"`
	Pools       []string          `json:"pools,omitempty"`
	Default     bool              `json:"default,omitempty"`
	Local       bool              `json:"local,omitempty"`
	CustomData  map[string]string `json:"custom_data,omitempty"`
	HttpProxy   string            `json:"httpProxy,omitempty"`

	KubeConfig *ClusterKubeConfig `json:"kubeConfig,omitempty"`
}
