/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.27
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type JobSpecContainer struct {
	Image   string   `json:"image,omitempty"`
	Envs    []EnvVar `json:"envs,omitempty"`
	Command []string `json:"command,omitempty"`
}
