/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Permission context
type EventPermissionContext struct {
	CtxType string `json:"CtxType,omitempty"`
	Value   string `json:"Value,omitempty"`
}
