/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.19
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type ClusterKubeConfigUser struct {
	Password              string                             `json:"password,omitempty"`
	ClientCertificateData string                             `json:"client-certificate-data,omitempty"`
	ClientKeyData         string                             `json:"client-key-data,omitempty"`
	AuthProvider          *ClusterKubeConfigUserAuthprovider `json:"auth-provider,omitempty"`
	Exec                  *ClusterKubeConfigUserExec         `json:"exec,omitempty"`
	Token                 string                             `json:"token,omitempty"`
	Username              string                             `json:"username,omitempty"`
}
