/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type EventLock struct {
	Type  string `json:"Type,omitempty"`
	Value string `json:"Value,omitempty"`
}
