/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Cluster struct {
	Name        interface{} `json:"name,omitempty"`
	Addresses   interface{} `json:"addresses,omitempty"`
	Provisioner interface{} `json:"provisioner,omitempty"`
	Cacert      []byte      `json:"cacert,omitempty"`
	Clientcert  []byte      `json:"clientcert,omitempty"`
	Clientkey   []byte      `json:"clientkey,omitempty"`
	Pools       interface{} `json:"pools,omitempty"`
	CustomData  interface{} `json:"custom_data,omitempty"`
	CreateData  interface{} `json:"create_data,omitempty"`
	Default_    interface{} `json:"default,omitempty"`
}
