/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type EventExtraTargets struct {
	Target EventLock `json:"Target,omitempty"`
	Lock   bool      `json:"Lock,omitempty"`
}
