/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.27
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type AppCertificatesCnames struct {
	Certificate string `json:"certificate"`
	Issuer      string `json:"issuer"`
}
