/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type UnitMetrics struct {
	Id     string `json:"id,omitempty"`
	Cpu    string `json:"cpu,omitempty"`
	Memory string `json:"memory,omitempty"`
}
