/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

import (
	"time"
)

type EventStructuredLog struct {
	Message string    `json:"Message,omitempty"`
	Date    time.Time `json:"Date,omitempty"`
}
