/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Arguments for updating an existing team token.
type TeamTokenUpdateArgs struct {
	Regenerate  `json:"regenerate,omitempty"`
	Description `json:"description,omitempty"`
	// Expire time in seconds, using a negative value removes the expiration.
	ExpiresIn `json:"expires_in,omitempty"`
}
