/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ServiceBrokerConfig struct {
	Insecure               `json:"Insecure,omitempty"`
	Context                `json:"Context,omitempty"`
	AuthConfig             `json:"AuthConfig,omitempty"`
	CacheExpirationSeconds `json:"CacheExpirationSeconds,omitempty"`
}
