/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.18
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type PoolConstraintSet struct {
	Append    bool     `json:"append,omitempty"`
	PoolExpr  string   `json:"PoolExpr,omitempty"`
	Field     string   `json:"Field,omitempty"`
	Values    []string `json:"Values,omitempty"`
	Blacklist bool     `json:"Blacklist,omitempty"`
}
