/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ServiceInstance struct {
	Name        interface{} `json:"name,omitempty"`
	Tags        interface{} `json:"tags,omitempty"`
	Id          interface{} `json:"id,omitempty"`
	ServiceName interface{} `json:"service_name,omitempty"`
	PlanName    interface{} `json:"plan_name,omitempty"`
	Apps        interface{} `json:"apps,omitempty"`
	BoundUnits  interface{} `json:"bound_units,omitempty"`
	Teams       interface{} `json:"teams,omitempty"`
	TeamOwner   interface{} `json:"team_owner,omitempty"`
	Description interface{} `json:"description,omitempty"`
}
