/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Parsed custom data
type EventCustomData struct {
	Start []map[string]interface{} `json:"Start,omitempty"`
	End   []map[string]interface{} `json:"End,omitempty"`
	Other []map[string]interface{} `json:"Other,omitempty"`
}
