/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Volume
type Volume struct {
	// Volume name.
	Name interface{} `json:"name,omitempty"`
	// Volume pool.
	Pool interface{} `json:"pool,omitempty"`
	// Team that owns the volume.
	TeamOwner interface{} `json:"teamOwner,omitempty"`
	// Volume status.
	Status interface{} `json:"status,omitempty"`
	// Volume plan.
	Plan interface{} `json:"plan,omitempty"`
	// Volume binds.
	Binds interface{} `json:"binds,omitempty"`
	// Custom volume options.
	Opts interface{} `json:"opts,omitempty"`
}
