/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Service struct {
	Service interface{} `json:"service,omitempty"`
	// [deprecated]
	Instances        interface{} `json:"instances,omitempty"`
	Plans            interface{} `json:"plans,omitempty"`
	ServiceInstances interface{} `json:"service_instances,omitempty"`
}
