/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Environment variable.
type Env struct {
	Name  interface{} `json:"name,omitempty"`
	Value interface{} `json:"value,omitempty"`
}
