/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type EventAllowed struct {
	Scheme   string                 `json:"Scheme,omitempty"`
	Contexts []EventAllowedContexts `json:"Contexts,omitempty"`
}
