/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.22
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type EventStartCustomData struct {
	Kind float32 `json:"Kind,omitempty"`
	Data string  `json:"Data,omitempty"`
}
