/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type CertIssuerSetData struct {
	Cname  string `json:"cname,omitempty"`
	Issuer string `json:"issuer,omitempty"`
}
