/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// Data sent to the environment set endpoint.
type EnvSetData struct {
	Envs      interface{} `json:"envs,omitempty"`
	Norestart interface{} `json:"norestart,omitempty"`
	Private   interface{} `json:"private,omitempty"`
}
