/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Lock struct {
	Locked      interface{} `json:"locked,omitempty"`
	Reason      interface{} `json:"reason,omitempty"`
	Owner       interface{} `json:"owner,omitempty"`
	AcquireDate interface{} `json:"acquireDate,omitempty"`
}
