/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Pool struct {
	Name        interface{} `json:"name,omitempty"`
	Default_    interface{} `json:"default,omitempty"`
	Provisioner interface{} `json:"provisioner,omitempty"`
	Public      interface{} `json:"public,omitempty"`
	Teams       interface{} `json:"teams,omitempty"`
	Allowed     interface{} `json:"allowed,omitempty"`
}
