/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type ServiceInstanceBoundUnit struct {
	AppName interface{} `json:"app_name,omitempty"`
	Id      interface{} `json:"id,omitempty"`
	Ip      interface{} `json:"ip,omitempty"`
}
