/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// ServiceBrokerConfigAuthConfig struct for ServiceBrokerConfigAuthConfig
type ServiceBrokerConfigAuthConfig struct {
	BasicAuthConfig ServiceBrokerConfigAuthConfigBasicAuthConfig `json:"BasicAuthConfig,omitempty"`
	BearerConfig    ServiceBrokerConfigAuthConfigBearerConfig    `json:"BearerConfig,omitempty"`
}
