/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

type EventKind struct {
	Type string `json:"Type,omitempty"`
	Name string `json:"Name,omitempty"`
}
