/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Event extra target
type EventExtraTarget struct {
	Target EventTarget `json:"Target,omitempty"`
	Lock   bool        `json:"Lock,omitempty"`
}
