/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.29
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tsuru

// Swap Units Auto Scale spec
type SwapAutoScaleSpec struct {
	Version string `json:"version"`
}
