/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Webhook struct {
	Name        interface{} `json:"name,omitempty"`
	Description interface{} `json:"description,omitempty"`
	TeamOwner   interface{} `json:"team_owner,omitempty"`
	EventFilter interface{} `json:"event_filter,omitempty"`
	Url         interface{} `json:"url,omitempty"`
	ProxyUrl    interface{} `json:"proxy_url,omitempty"`
	Headers     interface{} `json:"headers,omitempty"`
	Method      interface{} `json:"method,omitempty"`
	Body        interface{} `json:"body,omitempty"`
	Insecure    interface{} `json:"insecure,omitempty"`
}
