/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type Team struct {
	Name        interface{} `json:"name,omitempty"`
	Tags        interface{} `json:"tags,omitempty"`
	Permissions interface{} `json:"permissions,omitempty"`
}
