/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type PoolCreateData struct {
	Name        interface{} `json:"name,omitempty"`
	Public      interface{} `json:"public,omitempty"`
	Default_    interface{} `json:"default,omitempty"`
	Force       interface{} `json:"force,omitempty"`
	Provisioner interface{} `json:"provisioner,omitempty"`
}
