/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

// App plan.
type Plan struct {
	Name     interface{} `json:"name,omitempty"`
	Memory   interface{} `json:"memory,omitempty"`
	Swap     interface{} `json:"swap,omitempty"`
	Cpushare interface{} `json:"cpushare,omitempty"`
	Default_ interface{} `json:"default,omitempty"`
	Router   interface{} `json:"router,omitempty"`
}
