/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type NodeUpdateData struct {
	Address  interface{} `json:"address,omitempty"`
	Pool     interface{} `json:"pool,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	Enable   interface{} `json:"enable,omitempty"`
	Disable  interface{} `json:"disable,omitempty"`
}
