/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type NodeStatus struct {
	Address     interface{} `json:"address,omitempty"`
	Checks      interface{} `json:"checks,omitempty"`
	Lastsuccess interface{} `json:"lastsuccess,omitempty"`
	Lastupdate  interface{} `json:"lastupdate,omitempty"`
}
