/*
 * Tsuru
 *
 * Open source, extensible and Docker-based Platform as a Service (PaaS)
 *
 * API version: 1.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tsuru

type WebhookEventFilter struct {
	TargetTypes  interface{} `json:"target_types,omitempty"`
	TargetValues interface{} `json:"target_values,omitempty"`
	KindTypes    interface{} `json:"kind_types,omitempty"`
	KindNames    interface{} `json:"kind_names,omitempty"`
	ErrorOnly    interface{} `json:"error_only,omitempty"`
	SuccessOnly  interface{} `json:"success_only,omitempty"`
}
